 
 // 1 tapsyrma
 a = 10;
 b = 5;
 c = 2;

 let number= (a+c)-b;
 console.log (number)

 let sun=(a*b)/c;
 console.log (sun)

 //2 tapsyrma
 x = 7
 let q = x++ + ++x;
 console.log (a)
 let w = x-- - --x;
 console.log(w)

 //3 tapsyrma

 d=4;
 e=5;
 let r = "The result is: " + ( d + e )
 console.log (r)

 //4 tapsyrma

 let t = (a>b)&&(b>0)&&(a>0)
 console.log(t)

 let y = (c<10)||(c==2)
 console.log (y)


 a=10
 s=2
 let result =  (a/s != 5)
 console.log(result)

 //5 tapsyrma 
 a=10
 b="10"
 let k = (a == b)
 console.log(k)
 let f = (a === b)
 console.log (f)

 // 6 tapsyurma 
  let l = 32;
 let text =((l % 2 == 0)||(l % 3 == 0))&&(l % 6 != 0);
 console.log(text);

 y = 12
let sunber = ((y > 10) && (y < 5));
console.log(sunber);
